name: release
on:
  push:
    tags: ['*.*.*']
  workflow_dispatch:
jobs:
  release:
    permissions:
      contents: write
    uses: nimbase/setup-nim-action/.github/workflows/release_clue.yml@main
    with:
      nim-version: stable
      app-name: booyaka
      pre-build-command: |
        clue install supra
        clue build --verbose -d:release
